# Generated by Django 4.2.9 on 2024-01-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
